version: "3.8"

services:
  firestore-emulator:
    container_name: firestore-emulator
    image: google/cloud-sdk:415.0.0-emulators
    platform: linux/amd64
    expose:
      - 5173
    ports:
      - "5173:5173"
    command: [ "gcloud", "beta", "emulators", "firestore", "start", "--host-port=0.0.0.0:5173" ]

  k33-backend:
    container_name: k33-backend
    build: apps/k33-backend
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/config/gcp-service-account.json
      - FIRESTORE_EMULATOR_HOST=firestore-emulator:5173
      - JAVA_OPTS=-Dlogback.configurationFile=logback.xml
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - METRICS_ENABLED=false
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_ENABLED=false
      - LEGAL_SPACE_ID=${LEGAL_SPACE_ID}
      - LEGAL_SPACE_TOKEN=${LEGAL_SPACE_TOKEN}
      - RESEARCH_SPACE_ID=${RESEARCH_SPACE_ID}
      - RESEARCH_SPACE_TOKEN=${RESEARCH_SPACE_TOKEN}
      - ALGOLIA_APP_ID=${ALGOLIA_APP_ID}
      - ALGOLIA_API_KEY=${ALGOLIA_API_KEY}
      - SLACK_ALERTS_CHANNEL_ID=${SLACK_ALERTS_CHANNEL_ID}
      - SLACK_GENERAL_CHANNEL_ID=${SLACK_GENERAL_CHANNEL_ID}
      - SLACK_INVEST_CHANNEL_ID=${SLACK_INVEST_CHANNEL_ID}
      - SLACK_PRODUCT_CHANNEL_ID=${SLACK_PRODUCT_CHANNEL_ID}
      - SLACK_PROFESSIONAL_INVESTORS_CHANNEL_ID=${SLACK_PROFESSIONAL_INVESTORS_CHANNEL_ID}
      - SLACK_RESEARCH_CHANNEL_ID=${SLACK_RESEARCH_CHANNEL_ID}
      - SLACK_RESEARCH_EVENTS_CHANNEL_ID=${SLACK_RESEARCH_EVENTS_CHANNEL_ID}
      - SLACK_TOKEN=${SLACK_TOKEN}
      - INVEST_DENIED_COUNTRY_CODE_LIST=${INVEST_DENIED_COUNTRY_CODE_LIST}
      - INVEST_EMAIL_FROM=${INVEST_EMAIL_FROM}
      - INVEST_EMAIL_TO_LIST=${INVEST_EMAIL_TO_LIST}
      - INVEST_EMAIL_CC_LIST=${INVEST_EMAIL_CC_LIST}
      - INVEST_EMAIL_BCC_LIST=${INVEST_EMAIL_BCC_LIST}
    volumes:
      - "./infra/gcp/secrets/gcp-service-account.json:/config/gcp-service-account.json:ro"
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - firestore-emulator

  acceptance-tests:
    container_name: acceptance-tests
    build: apps/acceptance-tests
    environment:
      - BACKEND_HOST=k33-backend
      - GOOGLE_APPLICATION_CREDENTIALS=/config/gcp-service-account.json
      - LEGAL_SPACE_ID=${LEGAL_SPACE_ID}
      - PLATFORM_TNC_VERSION=${PLATFORM_TNC_VERSION}
      - PLATFORM_TNC_ENV_ID=${PLATFORM_TNC_ENV_ID}
      - PLATFORM_TNC_ENTRY_ID=${PLATFORM_TNC_ENTRY_ID}
      - TEST_PAGE_ID=${TEST_PAGE_ID}
      - TEST_REPORT_ID=${TEST_REPORT_ID}
    volumes:
      - "./infra/gcp/secrets/gcp-service-account.json:/config/gcp-service-account.json:ro"
    depends_on:
      - k33-backend