version: "3.8"

services:
  firestore-emulator:
    container_name: firestore-emulator
    image: google/cloud-sdk:373.0.0-emulators
    expose:
      - 5173
    ports:
      - "5173:5173"
    command: [ "gcloud", "beta", "emulators", "firestore", "start", "--host-port=0.0.0.0:5173" ]

  arcane-platform-app:
    container_name: arcane-platform-app
    build: apps/arcane-platform-app
    environment:
      - ENV=gcp
      - GOOGLE_APPLICATION_CREDENTIALS=/config/gcp-service-account.json
      - FIRESTORE_EMULATOR_HOST=firestore-emulator:5173
      - JAVA_OPTS=-Dlogback.configurationFile=logback.xml
    volumes:
      - ./infra/gcp/secrets:/config/:ro
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - firestore-emulator

  acceptance-tests:
    container_name: acceptance-tests
    build: apps/acceptance-tests
    environment:
      - BACKEND_HOST=arcane-platform-app
    depends_on:
      - arcane-platform-app