version: "3.8"

services:
  firestore-emulator:
    container_name: firestore-emulator
    image: google/cloud-sdk:397.0.0-emulators
    expose:
      - 5173
    ports:
      - "5173:5173"
    command: [ "gcloud", "beta", "emulators", "firestore", "start", "--host-port=0.0.0.0:5173" ]

  oauth2-provider-emulator:
    container_name: oauth2-provider-emulator
    build: apps/oauth2-provider-emulator
    expose:
      - 8080

  arcane-platform-app:
    container_name: arcane-platform-app
    build: apps/arcane-platform-app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/config/gcp-service-account.json
      - FIRESTORE_EMULATOR_HOST=firestore-emulator:5173
      - JAVA_OPTS=-Dlogback.configurationFile=logback.xml
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - METRICS_ENABLED=false
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_ENABLED=false
      - LEGAL_SPACE_ID=${LEGAL_SPACE_ID}
      - LEGAL_SPACE_TOKEN=${LEGAL_SPACE_TOKEN}
      - RESEARCH_SPACE_ID=${RESEARCH_SPACE_ID}
      - RESEARCH_SPACE_TOKEN=${RESEARCH_SPACE_TOKEN}
      - ALGOLIA_APP_ID=${ALGOLIA_APP_ID}
      - ALGOLIA_API_KEY=${ALGOLIA_API_KEY}
      - SLACK_ALERTS_CHANNEL_ID=${SLACK_ALERTS_CHANNEL_ID}
      - SLACK_ASSETS_CHANNEL_ID=${SLACK_ASSETS_CHANNEL_ID}
      - SLACK_GENERAL_CHANNEL_ID=${SLACK_GENERAL_CHANNEL_ID}
      - SLACK_PRODUCT_CHANNEL_ID=${SLACK_PRODUCT_CHANNEL_ID}
      - SLACK_PROFESSIONAL_INVESTORS_CHANNEL_ID=${SLACK_PROFESSIONAL_INVESTORS_CHANNEL_ID}
      - SLACK_RESEARCH_CHANNEL_ID=${SLACK_RESEARCH_CHANNEL_ID}
      - SLACK_RESEARCH_EVENTS_CHANNEL_ID=${SLACK_RESEARCH_EVENTS_CHANNEL_ID}
      - SLACK_TOKEN=${SLACK_TOKEN}
      - INVEST_DENIED_COUNTRY_CODE_LIST=${INVEST_DENIED_COUNTRY_CODE_LIST}
      - INVEST_EMAIL_FROM=${INVEST_EMAIL_FROM}
      - INVEST_EMAIL_TO_LIST=${INVEST_EMAIL_TO_LIST}
      - INVEST_EMAIL_CC_LIST=${INVEST_EMAIL_CC_LIST}
      - INVEST_EMAIL_BCC_LIST=${INVEST_EMAIL_BCC_LIST}
    volumes:
      - "./infra/gcp/secrets/gcp-service-account.json:/config/gcp-service-account.json:ro"
    expose:
      - 8080
    depends_on:
      - firestore-emulator

  test.api.arcane.no:
    container_name: esp
    image: gcr.io/endpoints-release/endpoints-runtime:2
    command: >
      --listener_port=8080
      --backend=http://arcane-platform-app:8080
      --service=test.api.arcane.no
      --rollout_strategy=managed
      --non_gcp
      --service_account_key=/config/gcp-service-account.json
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - "./infra/gcp/secrets/gcp-service-account.json:/config/gcp-service-account.json:ro"
    depends_on:
      - oauth2-provider-emulator
      - arcane-platform-app

  acceptance-tests:
    container_name: acceptance-tests
    build: apps/acceptance-tests
    environment:
      - BACKEND_HOST=test.api.arcane.no
      - GOOGLE_APPLICATION_CREDENTIALS=/config/gcp-service-account.json
      - LEGAL_SPACE_ID=${LEGAL_SPACE_ID}
      - PLATFORM_TNC_VERSION=${PLATFORM_TNC_VERSION}
      - PLATFORM_TNC_ENV_ID=${PLATFORM_TNC_ENV_ID}
      - PLATFORM_TNC_ENTRY_ID=${PLATFORM_TNC_ENTRY_ID}
      - TEST_PAGE_ID=${TEST_PAGE_ID}
      - TEST_REPORT_ID=${TEST_REPORT_ID}
    volumes:
      - "./infra/gcp/secrets/gcp-service-account.json:/config/gcp-service-account.json:ro"
    depends_on:
      - test.api.arcane.no
      - oauth2-provider-emulator