version: "3.8"

services:
  arcane-platform-app:
    container_name: arcane-platform-app
    image: arcane-platform-app
    environment:
      - ENV=gcp
      - GOOGLE_APPLICATION_CREDENTIALS=/config/arcane-platform-prod.json
    volumes:
      - "./infra/gcp/secrets/arcane-platform-prod.json:/config/arcane-platform-prod.json:ro"
    expose:
      - 8080
    entrypoint: [ "java", "-cp", "@/app/jib-classpath-file", "io.ktor.server.netty.EngineMain" ]

  test.api.arcane.no:
    container_name: esp
    image: gcr.io/endpoints-release/endpoints-runtime:2
    command: >
      --listener_port=8080
      --backend=http://arcane-platform-app:8080
      --service=test.api.arcane.no
      --rollout_strategy=managed
      --non_gcp
      --service_account_key=/config/arcane-platform-prod.json
    ports:
      - "8080:8080"
    volumes:
      - "./infra/gcp/secrets/arcane-platform-prod.json:/config/arcane-platform-prod.json:ro"
    depends_on:
      - arcane-platform-app

#  acceptance-tests:
#    container_name: acceptance-tests
#    image: acceptance-tests
#    environment:
#      - BACKEND_HOST=test.api.arcane.no
#    command: [ "--select-package=no.arcane.platform.tests" ]
#    depends_on:
#      - test.api.arcane.no