name: Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "feature/**"
  push:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
      - name: Setup jdk17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
#          cache: "gradle"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build arcane-platform-app docker image with gradle
        run: ./gradlew --no-daemon :apps:arcane-gcp-platform-app:jibDockerBuild
      - name: Build acceptance-tests docker image with gradle
        run: ./gradlew --no-daemon :apps:acceptance-tests:jibDockerBuild
      - name: Load github env secrets
        env:
          CONTENTFUL_CONFIG: ${{ secrets.CONTENTFUL_CONFIG }}
        run: echo ${CONTENTFUL_CONFIG} >> .github/config/contentful-github.conf
      - name: Run docker compose based system integration tests
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: docker-compose -f docker-compose.yaml -f docker-compose.github.yaml up --build --abort-on-container-exit
