name: Test feature branch
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "feature/**"
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
      - name: Setup jdk16
        uses: actions/setup-java@v2
        with:
          java-version: "16"
          distribution: "adopt"
          architecture: x64
#          cache: "gradle"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build arcane-platform-app docker image with gradle
        run: ./gradlew --no-daemon :apps:arcane-gcp-platform-app:jibDockerBuild
      - name: Build acceptance-tests docker image with gradle
        run: ./gradlew --no-daemon :apps:acceptance-tests:jibDockerBuild
      - name: Run docker compose based system integration tests
        run: docker-compose up --build --abort-on-container-exit