name: Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "feature/**"
  push:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - name: Setup jdk19
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "19.0.2"
#          cache: "gradle"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew --no-daemon installDist --parallel
      - name: Load secrets
        uses: 1password/load-secrets-action@v1
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GCP_SA_KEY: op://env/github/gcp-dev/GCP_SA_KEY
      - name: Load secrets into files
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo "${ENV_FILE}" >> .env
          echo "${GCP_SA_KEY}" >> infra/gcp/secrets/gcp-service-account.json
      - name: Run docker compose based system integration tests
        run: docker compose up --build --abort-on-container-exit
