name: Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "feature/**"
  push:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - name: Setup jdk18
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "18.0.1"
#          cache: "gradle"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew --no-daemon installDist --parallel
      - name: Load github env secrets
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "${ENV_FILE}" >> .env
          echo "${GCP_SA_KEY}" >> infra/gcp/secrets/gcp-service-account.json
      - name: Run docker compose based system integration tests
        run: docker compose -f docker-compose.no-esp.yaml up --build --abort-on-container-exit
