name: Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "feature/**"
  push:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
      - name: Setup jdk17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
#          cache: "gradle"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew --no-daemon installDist --parallel
      - name: Load github env secrets
        env:
          CONTENTFUL_CONFIG: ${{ secrets.CONTENTFUL_CONFIG }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "${CONTENTFUL_CONFIG}" >> .github/config/contentful-github.conf
          echo "${GCP_SA_KEY}" >> .github/config/gcp-service-account.json
      - name: Run docker compose based system integration tests
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: docker compose -f docker-compose.yaml -f docker-compose.github.yaml up --build --abort-on-container-exit
